### ISSUE TITLE
Few issues with file version

### ISSUE THREAD

**Issue by DanAvni** [newky2k/VersionChangerAddin#24]
Please show in the project list the file version next to the assembly version. In my project I am changing the file version and it would be nice if it was listed

Also, My file version is currently 2022.1.223 (4th value is not set), when checking the checkbox "Use seperate versions" the file version that appears is 2022.1.223.-1 (but when trying to save it throws an error). Please add support for setting some of the version number fields empty (as long as the following fields are also empty obviously) so one could even set the version as 2022.1 or 2022

Thanks

**Comment by newky2k** [comment]
@DanAvni  Thanks for the suggestions about the file version.  I'll look into see what we can do with that in the projects list.

Re the seperate versions bug, i'll take a look it must be an issue with the version parser that is not setting it on the file revision field.

I'll take a look at the version concatination code so that you can leave some of the fields blank and use short numbers.

Thanks for the feedback!

**Comment by newky2k** [comment]
@DanAvni I going to pushing out an update later that fixes some of the issues you have been having with the file versions.

Please let me know if this doesn't fix the issue

**Comment by DanAvni** [comment]
@newky2k , I finally got to test the new version. It is working better but I cannot set the file version to 2022.2.630 (when setting the last part to empty, it changes back to 0 so the version is then set to 2022.2.630.0, although the file version on the project list only shows 2022.2.630"

If this is proving problematic, maybe you can add a combo box nect to the file version and assembly version where I can specify the format to use
1
1.2
1.2.3
1.2.3.4
The format can be detected from what is already in the assembly info

**Comment by newky2k** [comment]
@DanAvni I'll have a think about the best way to implement a varible lengh version number and how to update the business logic to accomodate it.
